config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :countries
  resources :departments
  resources :cities
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :department
end 

app/models/country.rb
class Country < ApplicationRecord
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :country
  has_many :cities
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token, if: :json_request?

  private

  def json_request?
    request.format.json?
  end
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: %i[ show edit update destroy ]

  # GET /countries or /countries.json
  def index
    @countries = Country.all
  end

  # GET /countries/1 or /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries or /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: "Country was successfully created." }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1 or /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: "Country was successfully updated." }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1 or /countries/1.json
  def destroy
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_path, status: :see_other, notice: "Country was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def country_params
      params.require(:country).permit(:name, :code_postal)
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_path, status: :see_other, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :code_postal, :country_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @countries = Country.all
    @departments = Department.all
    @cities = City.all
  end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_path, status: :see_other, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :lastname, :photo, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/_form.html.erb
<%= form_with(model: city) do |form| %>
  <% if city.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "Nombre", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :code_postal, "Código Postal", class: "form-label" %>
    <%= form.text_field :code_postal, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :department_id, "Departamento", class: "form-label" %>
    <%= form.collection_select :department_id, Department.all, :id, :name, { prompt: "Seleccione un departamento" }, { class: "form-select" } %>
  </div>

  <div>
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %> 

app/views/cities/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ciudades</h1>

<div id="cities">
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Código Postal</th>
        <th>Departamento</th>
        <th>País</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @cities.each do |city| %>
        <tr>
          <td><%= city.name %></td>
          <td><%= city.code_postal %></td>
          <td><%= city.department&.name %></td>
          <td><%= city.department&.country&.name %></td>
          <td>
            <%= link_to "Ver", city, class: "btn btn-info btn-sm" %>
            <%= link_to "Editar", edit_city_path(city), class: "btn btn-warning btn-sm" %>
            <%= button_to "Eliminar", city, method: :delete, class: "btn btn-danger btn-sm", form: { data: { turbo_confirm: "¿Estás seguro?" } } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Nueva Ciudad", new_city_path, class: "btn btn-primary" %> 

app/views/countries/_country.html.erb
<div id="<%= dom_id country %>">
  <p>
    <strong>Name:</strong>
    <%= country.name %>
  </p>

  <p>
    <strong>Code postal:</strong>
    <%= country.code_postal %>
  </p>

</div>

app/views/countries/_form.html.erb
<%= form_with(model: country) do |form| %>
  <% if country.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
        <% country.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :code_postal, style: "display: block" %>
    <%= form.text_field :code_postal %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Show this country", @country %> |
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Países</h1>

<div id="countries">
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Código Postal</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @countries.each do |country| %>
        <tr>
          <td><%= country.name %></td>
          <td><%= country.code_postal %></td>
          <td>
            <%= link_to "Ver", country, class: "btn btn-info btn-sm" %>
            <%= link_to "Editar", edit_country_path(country), class: "btn btn-warning btn-sm" %>
            <%= button_to "Eliminar", country, method: :delete, class: "btn btn-danger btn-sm", form: { data: { turbo_confirm: "¿Estás seguro?" } } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Nuevo País", new_country_path, class: "btn btn-primary" %>

app/views/countries/new.html.erb
<h1>New country</h1>

<%= render "form", country: @country %>

<br>

<div>
  <%= link_to "Back to countries", countries_path %>
</div>

app/views/countries/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @country %>

<div>
  <%= link_to "Edit this country", edit_country_path(@country) %> |
  <%= link_to "Back to countries", countries_path %>

  <%= button_to "Destroy this country", @country, method: :delete %>
</div>

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

  <p>
    <strong>Code postal:</strong>
    <%= department.code_postal %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= department.country_id %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, "Nombre", class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :code_postal, "Código Postal", class: "form-label" %>
    <%= form.text_field :code_postal, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :country_id, "País", class: "form-label" %>
    <%= form.collection_select :country_id, Country.all, :id, :name, { prompt: "Seleccione un país" }, { class: "form-select" } %>
  </div>

  <div>
    <%= form.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department %> |
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departamentos</h1>

<div id="departments">
  <table class="table">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Código Postal</th>
        <th>País</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      <% @departments.each do |department| %>
        <tr>
          <td><%= department.name %></td>
          <td><%= department.code_postal %></td>
          <td><%= department.country&.name %></td>
          <td>
            <%= link_to "Ver", department, class: "btn btn-info btn-sm" %>
            <%= link_to "Editar", edit_department_path(department), class: "btn btn-warning btn-sm" %>
            <%= button_to "Eliminar", department, method: :delete, class: "btn btn-danger btn-sm", form: { data: { turbo_confirm: "¿Estás seguro?" } } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to "Nuevo Departamento", new_department_path, class: "btn btn-primary" %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>

  <%= button_to "Destroy this department", @department, method: :delete %>
</div>

app/views/home/index.html.erb
<div class="container mt-4">
  <h1 class="text-center mb-4">Sistema de Gestión de Ubicaciones</h1>

  <!-- Países -->
  <div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h2 class="h4 mb-0">Países</h2>
      <%= link_to "Nuevo País", new_country_path, class: "btn btn-primary btn-sm" %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Código Postal</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @countries.each do |country| %>
              <tr>
                <td><%= country.name %></td>
                <td><%= country.code_postal %></td>
                <td>
                  <%= link_to "Ver", country, class: "btn btn-info btn-sm" %>
                  <%= link_to "Editar", edit_country_path(country), class: "btn btn-warning btn-sm" %>
                  <%= button_to "Eliminar", country, method: :delete, class: "btn btn-danger btn-sm", form: { data: { turbo_confirm: "¿Estás seguro?" } } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <!-- Departamentos -->
  <div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h2 class="h4 mb-0">Departamentos</h2>
      <%= link_to "Nuevo Departamento", new_department_path, class: "btn btn-primary btn-sm" %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Código Postal</th>
              <th>País</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @departments.each do |department| %>
              <tr>
                <td><%= department.name %></td>
                <td><%= department.code_postal %></td>
                <td><%= department.country&.name %></td>
                <td>
                  <%= link_to "Ver", department, class: "btn btn-info btn-sm" %>
                  <%= link_to "Editar", edit_department_path(department), class: "btn btn-warning btn-sm" %>
                  <%= button_to "Eliminar", department, method: :delete, class: "btn btn-danger btn-sm", form: { data: { turbo_confirm: "¿Estás seguro?" } } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <!-- Ciudades -->
  <div class="card mb-4">
    <div class="card-header d-flex justify-content-between align-items-center">
      <h2 class="h4 mb-0">Ciudades</h2>
      <%= link_to "Nueva Ciudad", new_city_path, class: "btn btn-primary btn-sm" %>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Nombre</th>
              <th>Código Postal</th>
              <th>Departamento</th>
              <th>País</th>
              <th>Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @cities.each do |city| %>
              <tr>
                <td><%= city.name %></td>
                <td><%= city.code_postal %></td>
                <td><%= city.department&.name %></td>
                <td><%= city.department&.country&.name %></td>
                <td>
                  <%= link_to "Ver", city, class: "btn btn-info btn-sm" %>
                  <%= link_to "Editar", edit_city_path(city), class: "btn btn-warning btn-sm" %>
                  <%= button_to "Eliminar", city, method: :delete, class: "btn btn-danger btn-sm", form: { data: { turbo_confirm: "¿Estás seguro?" } } %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiPrimeraChamba</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :lastname, style: "display: block" %>
    <%= form.text_field :lastname %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.number_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Name:</strong>
    <%= user.name %>
  </p>

  <p>
    <strong>Lastname:</strong>
    <%= user.lastname %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= user.photo %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= user.age %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user hola", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>